In [1]:
import numpy as np # numerical python
import netCDF4 as nc

In [2]:
spy = np.array([1, 4, 5.0, 6])

In [3]:
type(spy)

numpy.ndarray

In [4]:
print(spy.shape) # tamaño de variable spy
print(np.shape(spy))
print(spy[3])
print(spy[-1])

(4,)
(4,)
6.0
6.0


In [6]:
fileobj = nc.Dataset('ERA5_Coarse.nc')

In [8]:
lon = fileobj['longitude']
lat = fileobj['latitude']

In [9]:
print(fileobj)

<class 'netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    history: Thu Dec  1 13:02:52 2022: ncks -F -d time,1,,4 ERA5_Coarse.nc ERA5_test.nc
Wed Nov 30 09:40:40 2022: ncks -F -d time,1,,10 ERA5_Coarse.nc ERA5_test.nc
    NCO: netCDF Operators version 4.7.6 (Homepage = http://nco.sf.net, Code = http://github.com/nco/nco)
    dimensions(sizes): latitude(180), longitude(360), time(19)
    variables(dimensions): float32 latitude(latitude), float32 longitude(longitude), int16 sp(time, latitude, longitude), int16 sst(time, latitude, longitude), int16 t2m(time, latitude, longitude), float32 t2m_F(time, latitude, longitude), int32 time(time), int16 tp(time, latitude, longitude), int16 u10(time, latitude, longitude), int16 v10(time, latitude, longitude)
    groups: 


In [12]:
# Guarda en la memoria virtual estas variables
lon = fileobj['longitude']
lat = fileobj['latitude']
time = fileobj['time']

In [13]:
sst = fileobj['sst']

In [14]:
sst = fileobj['sst'][:]

In [15]:
print(np.shape(sst))

(19, 180, 360)


In [16]:
print(sst.std())
print(np.std(sst))

11.655968324582686
11.655968324582686


In [18]:
sst_C = sst - 273.15

In [19]:
print(np.mean(sst_C, axis=0).shape)

(180, 360)


In [20]:
np.mean(sst_C, axis=0).mean(axis=1)

masked_array(data=[-1.6900546635534965, -1.690051416304578,
                   -1.690049341673324, -1.6900467258339171,
                   -1.6900423961686917, -1.6900365330803657,
                   -1.6898238382761759, -1.6845676800983087,
                   -1.640277240795779, -1.5453931650084753,
                   -1.4157694110281362, -1.2815392305940898,
                   -1.1455699870376228, -0.9709779779625464,
                   -0.7244421551146182, -0.5243559563364235,
                   -0.2784883964530478, 0.08101306152140239,
                   0.4182163486554386, 0.7990733099364833,
                   0.9200757401857499, 1.0486383749996335,
                   1.4911550840076393, 2.0799568414636247,
                   2.5652982541989173, 2.929811696775026,
                   3.644901650973757, 3.7680883879972153,
                   4.090082237661396, 4.426223420538322, 4.79820863004297,
                   5.293147943410754, 5.621680820505642,
                   5.94431952

In [21]:
a = np.array([[1, 2], [3, 4]], float) # crear una matriz de dos dimensiones tipo float
b = np.array([[5, 6], [7,8]], float)

print('Matrix A')
print(a)
print('Matrix B')
print(b)

Matrix A
[[1. 2.]
 [3. 4.]]
Matrix B
[[5. 6.]
 [7. 8.]]


In [22]:
np.concatenate((a,b), axis=1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])